# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: JJK-UI-$(date:yyyyMMdd)$(rev:.rr)

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: 'build'
  condition: succeeded()
  displayName: 'build-ui'
  jobs:
  - job:
    condition: succeeded()
    displayName: 'install and build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build --prod
      displayName: 'npm install and build'

- stage: 'test'
  condition: succeeded()
  displayName: 'test-ui'
  jobs:
  - job:
    condition: succeeded()
    displayName: 'test run'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js testing'

      - script: |
          npm install -g @angular/cli
          npm install
          ng test 
        displayName: 'npm install and test'

- stage: 'mirror'
  condition: succeeded() 
  dependsOn: 
    - build
    - test
  displayName: 'mirror-ui'
  jobs:
    - job:
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
      displayName: 'mirror to CodeCommit'
      steps:
      - task: mirror-git-repository-vsts-task@1
        inputs:
          sourceGitRepositoryUri: '$(Build.Repository.Uri)'
          destinationGitRepositoryUri: '$(DestinationRepo)'
          destinationGitRepositoryPersonalAccessToken: '$(AccessID):$(AccessKey)'
        displayName: 'Final destination'

- stage: 'deploy'
  condition: succeeded() 
  dependsOn: 
    - mirror
  displayName: 'deploy-ui'
  jobs:
    - job:
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
      displayName: 'trigger CodeCommit build'
      steps:
      - task: CmdLine@2
        inputs:
          script: 'curl -X POST -d {} $(AMPLIFYWEBHOOK) -H "Content-Type:application/json"'
        displayName: 'curl command'